package com.github.demidko.aot;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;

/** Run once against the original JAR. Authored queries are not generated by the analyzer. */
public class ReviewCorpus {
  public static void main(String[] args) throws Exception {
    List<String> observed = new ArrayList<>();
    for (String query : Files.readAllLines(Paths.get(args[0]), StandardCharsets.UTF_8)) {
      String[] fields = query.split("\t", -1);
      observed.add(query + "\t" + WordformMeaning.lookupForMeanings(fields[1]).size());
    }
    Files.write(Paths.get(args[1]), observed, StandardCharsets.UTF_8);
    RuntimeEvidence.print();
  }
}
